owner: Mindjoy
repo: status

sites:
  - name: www.mindjoy.com
    url: https://mindjoy.com/
  - name: beta.mindjoy.com
    url: https://beta.mindjoy.com/
  - name: Platform
    url: $API_URL

assignees:
  - diraulo
  - EthanMarrs

status-website:
  cname: status.mindjoy.com
  logoUrl: https://raw.githubusercontent.com/Mindjoy/status/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/Mindjoy/status/master/assets/favicon.ico
  name: Status
  theme: light
